// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML;
using System;
using static Ml_pred_ConsoleApp1.Ml_pred;
using Microsoft.ML.Transforms.TimeSeries;

namespace Ml_pred_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var context = new MLContext();

            var data = context.Data.LoadFromTextFile<ModelInput>("D:/loadData.csv",
                hasHeader: true, separatorChar: ';');

            var pipeline = context.Regression.Trainers.Sdca(
                "DAYF",
                nameof(ModelInput.DAY7)
                ); ;
            var model = pipeline.Fit(data);

            var forecastingEngine = model.CreateTimeSeriesEngine<ModelInput, ModelOutput>(context);

            var forecasts = forecastingEngine.Predict(horizon:24);

            foreach (var forecastValue in forecasts.DAYF)
            {
                Console.WriteLine(forecastValue);
            }

            Console.ReadLine();
            // predict with default option.
            //var modelOutput = Ml_pred.Predict();
            //Console.WriteLine(string.Join(",", modelOutput.DAYF));

            // predict next 5 periods
            //modelOutput = Ml_pred.Predict(horizon: 5);
            //Console.WriteLine(string.Join(",", modelOutput.DAYF));

            // update and predict model
            // TBD
        }
    }
}

